# Generated by Django 5.2.4 on 2025-08-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mechanical_Texbook',
            new_name='Mechanical_Textbook',
        ),
    ]
