# Generated by Django 5.2.4 on 2025-08-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanical_Texbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.author')),
            ],
            options={
                'permissions': [('can_view', 'can view mechanical'), ('can_create', 'can create mechanical book'), ('can_edit', 'can edit mechanical book'), ('can_delete', 'can delete mechanical book')],
            },
        ),
    ]
