# Generated by Django 5.2.4 on 2025-08-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_mechanical_texbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanical_texbooks',
            options={'permissions': [('can_view', 'can view mechanical books'), ('can_create', 'can create mechanical books'), ('can_edit', 'can edit mechanical books'), ('can_delete', 'can delete mechanical books')]},
        ),
    ]
