# Generated by Django 5.2.4 on 2025-08-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_mechanical_texbooks_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mechanical_Texbooks',
            new_name='Mechanical_Texbook',
        ),
    ]
