# Generated by Django 5.2.4 on 2025-08-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add book'), ('can_change_book', 'can change book'), ('can_delete_book', 'can delete book')]},
        ),
    ]
